### ISSUE TITLE
Doesn't mark as viewed

### ISSUE THREAD

**Issue by freijon** [tegon/traktflix#2]
After successfully scrobbling an episode/movie to trakt.tv for the full length of the video, the episode/movie doesn't get marked as "viewed". I have to manually mark the episoded I watched.

**Comment by tegon** [comment]
Could you provide more details on this? I tested an episode here and it got marked as watched correctly. 
When you started watching, Trakt displayed the progress? Did you see any errors on console? This happened with a episode in particular or with anything you watched?

**Comment by freijon** [comment]
I watched several BoJack Horseman episodes. On my profile on Trakt it showed me the progress correclty. What might cause the problem is that I'm watching with Chromecast. But again, the progressbar on Trakt shows the correct information and the Traktflix logo turns red when playing. Haven't checked the console, I'll try that in the evening.

**Comment by tegon** [comment]
Never tested with a chromecast, but if the progress showed on trakt, the scrobble started correctly. The issue may be on the stop step. Can you tell where clicked? (Back to browse, next episode, etc)

**Comment by freijon** [comment]
I either clicked on the "stacked window" symbol in the player where you can choose between episodes or I did nothing at all (let the episode run out). When connected to the Chromecast it then jumps to the main Netflix homepage. I'll now test how it behaves when I watch an episode on my laptop without the Chromecast.

**Comment by tegon** [comment]
Clicking on other episode on stacked window worked correctly, but letting the episode run out to another, there I found an issue. I am listening to popstate, so the scrobble pauses when the page backs to navigation, but in this case only the querystring change in the url. I'll see what I can do to fix this.
Thank you for reporting this bug!

**Comment by tegon** [comment]
Fixed on v1.0.4.4573

**Comment by skotsjedal** [comment]
I have this issue still, correctly tracks "now playing" but at the end, wether I let it run to the next episode, or if I click back to browse or the x when it's waiting for the next episode. It never permanently tracks it. No Chromecast involved

**Comment by tegon** [comment]
Are you using last version? Also, can you tell me if are any erros on console?
The stop action should be called whenever an episode or movie ends, either by clicking on other links or if another episode starts. You can se on network tab in chrome developer tools, like in this screenshot:
![screenshot 2015-09-18 09 46 25](https://cloud.githubusercontent.com/assets/3727827/9959443/764806ac-5dea-11e5-8c5f-35fa1a6bb5fa.png)
The progress must be at least 80% to trakt consider it as "watched".
Could you check in your developer tools what is happening?

**Comment by skotsjedal** [comment]
version 1.0.4.4574
Watched something just now, epose was showing underway on trakt.tv but it didn't record the first episode (didn't have console open when it changed, opened it after and no errors). Let the next episode play though, that one did record.

**Comment by skotsjedal** [comment]
Tried again, it sends a stop but progress is only 76.61 although I watched it all from start to finish

start
```
{"episode":{"season":4,"number":12,"title":"Campaign Ad","ids":{"trakt":406268,"tvdb":4200379,"imdb":null,"tmdb":397684,"tvrage":null},"images":{"screenshot":{"full":"https://walter.trakt.us/images/episodes/000/406/268/screenshots/original/60d5730a42.jpg","medium":"https://walter.trakt.us/images/episodes/000/406/268/screenshots/medium/60d5730a42.jpg","thumb":"https://walter.trakt.us/images/episodes/000/406/268/screenshots/thumb/60d5730a42.jpg"}}},"progress":0.04}
```

stoo
```
{"episode":{"season":4,"number":12,"title":"Campaign Ad","ids":{"trakt":406268,"tvdb":4200379,"imdb":null,"tmdb":397684,"tvrage":null},"images":{"screenshot":{"full":"https://walter.trakt.us/images/episodes/000/406/268/screenshots/original/60d5730a42.jpg","medium":"https://walter.trakt.us/images/episodes/000/406/268/screenshots/medium/60d5730a42.jpg","thumb":"https://walter.trakt.us/images/episodes/000/406/268/screenshots/thumb/60d5730a42.jpg"}}},"progress":76.61}
```

start on next episode
```
{"episode":{"season":4,"number":13,"title":"Bowling for Votes","ids":{"trakt":406269,"tvdb":4204799,"imdb":null,"tmdb":397682,"tvrage":null},"images":{"screenshot":{"full":"https://walter.trakt.us/images/episodes/000/406/269/screenshots/original/4d8d72c3c0.jpg","medium":"https://walter.trakt.us/images/episodes/000/406/269/screenshots/medium/4d8d72c3c0.jpg","thumb":"https://walter.trakt.us/images/episodes/000/406/269/screenshots/thumb/4d8d72c3c0.jpg"}}},"progress":null}
```

**Comment by tegon** [comment]
The progress comes from the player progress bar width, basically this code:
```javascript
document.getElementsByClassName('player-scrubber-progress-completed')[0].style.width
```
Is there any chances that the episode you watched went to the credits too soon?

**Comment by 112358z** [comment]
I am facing this issue currently.

**Comment by tegon** [comment]
Can you provide more info like the ones above?
